name: GitHub Actions Demo
on: [push]
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test1"
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test2"
  jobs3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test3"


